name: PMD Code Quality Check

on:
  push:
    branches:
      - '*'  # Runs on all branches

permissions:
  contents: read
  security-events: write
  actions: write

jobs:
  code_quality:
    name: Run PMD Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Execute PMD Scan
        uses: pmd/pmd-github-action@v2
        with:
          version: '7.0.0-rc4'
          sourcePath: 'src/'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
          analyzeModifiedFilesOnly: false

      - name: Upload PMD Scan Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

      - name: Store PMD Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmd-sarif-report
          path: pmd-report.sarif
          retention-days: 5
